[package]
    name = "morphology_wizard"
    version = "1.0.0"
    edition = "2021"
    description = "Create realistic neuron morphologies"
    authors = ["David McDougall <dam1784@rit.edu>"]
    license = "Proprietary"
    repository = ""

[lib]
    crate-type = ["cdylib", "rlib"]

[dependencies]
    bitvec = "1"
    kiddo = "4"
    pyo3 = { version = "0.21", features = ["extension-module", "multiple-pymethods", "serde"], optional = true }
    serde = { version = "1", features = ["derive"] }
