[package]
    name = "morphology_wizard"
    edition = "2021"
    version = "1.0.0"
    authors = ["David McDougall <dam1784@rit.edu>"]
    license = "Proprietary"
    description = "Create realistic neuron morphologies"

[lib]
    crate-type = ["cdylib", "rlib"]

[dependencies]
    bitvec = "1"
    kiddo = "4"
    num-traits = "0.2"
    numpy = "0.21"
    pyo3 = {version = "0.21", features = ["extension-module", "multiple-pymethods", "serde"], optional = true}
    serde = {version = "1", features = ["derive"]}
