[build-system]
    requires = ["maturin>=1.0,<2.0"]
    build-backend = "maturin"

[tool.maturin]
    module-name = "morphology_wizard"
    features = ["pyo3"]
    profile = "release"

[project]
    name = "morphology_wizard"
