[build-system]
    requires = ["setuptools >= 61.0"]
    build-backend = "setuptools.build_meta"

[project]
    name = "morphology_wizard"
    version = "1.0.0"
    dependencies = [
        "panda3d",
    ]
